### ISSUE TITLE
Gitbook to Slack webhook not working

### ISSUE THREAD

**Issue by SeaDude** [GitbookIO/services-slack#2]
Steps: 
1. Created a webhook in Slack with URL:  https://hooks.slack.com/services/<long-hex-dec>
2. Copied the <long-hex-dec> above
3. Pasted https://slack-service.gitbook.com/hook/v1/<long-hex-dec> into "Settings/Webhooks/Payload URL" of my gitbook.
4. Make change to 
5. Get `failed` message in my Gitbook Webhook (See attached)

![screenshot from 2016-06-27 18-58-40](https://cloud.githubusercontent.com/assets/8636973/16401435/56998dec-3c99-11e6-8f28-0cd7fcdc9311.png)
![screenshot from 2016-06-27 18-58-31](https://cloud.githubusercontent.com/assets/8636973/16401436/5699ea9e-3c99-11e6-9b37-c9e936a158c1.png)

I've been seeking advice and trying different things for a week now. Any help is appreciated. 

Thanks

**Comment by SamyPesse** [comment]
It should be fixed now.
